### ISSUE TITLE
How do I start it up?

### ISSUE THREAD

**Issue by Ved-un** [VHSgunzo/udev-notify#1]
Hello.
It doesn't work for some reason.

**Comment by VHSgunzo** [comment]
Hello. What is your system, and do you have all the dependencies installed?

udev-notify starts working immediately after installation, if you have all the dependencies installed.

**Comment by Ved-un** [comment]
Thanks for the quick response.
I have Arch Linux. 
I installed it like you wrote, with the command `yay --needed --noconfirm -S base-devel udev-notify-git`

What else could be missing? 
I'll try restarting the computer now, although I've tried that before...

**Comment by Ved-un** [comment]
After rebooting, it doesn't work either.
Checked thoroughly now - all dependencies are installed, except for `espeak-ng`
```
usbutils
libnotify
sox
espeak-ng
sed
coreutils
gawk
grep
util-linux
bash
```

Could there be a problem with the PKGBUILD in the AUR?

**Comment by Ved-un** [comment]
Сейчас попробовал установить из исходников через `sudo make install` и всё равно не работает...
Что хоть может быть?
```
[elem] ~/udev-notify ❯ sudo make install                                                     (18:57)
install -Dm755 udev-notify "/usr/bin/udev-notify"
install -Dm644 LICENSE "/usr/share/licenses/udev-notify/LICENSE"
for ICON in $(ls icons) ; do \
install -Dm644 icons/$ICON "/usr/share/udev-notify/icons/$ICON" ; \
done
for SOUND in $(ls sounds) ; do \
install -Dm644 sounds/$SOUND "/usr/share/udev-notify/sounds/$SOUND" ; \
done
install -Dm644 99-udev-notify.rules "/etc/udev/rules.d/99-udev-notify.rules"
[elem] ~/udev-notify ❯
```

**Comment by VHSgunzo** [comment]
Это очень странно, я проверял на нескольких разных дистрах (fedora, debian, arch-подобные) и везде работало.
USB-девайс, который используется для проверки, точно работает?
Может попробовать на другом?
Так же проверьте создается ли список подключенных USB устройств '/var/tmp/udev-notify-devices'
и изменяется ли он при их подключении и отключении

**Comment by Ved-un** [comment]
Да нет... конечно же я попробовал различные флэшки...
У меня используется не DE, а чистый WM (BSPWM) - может из за этого...

Перед этим пробовал это https://github.com/eworm-de/udev-block-notify но у него видимо принцип другой и оно у меня работает... но мне оно ненужно - оно перегружено и на всех дисках показывает, мне нужно только USB...

Сейчас поставил это https://github.com/wcampbell0x2a/usb-notify и оно тоже у меня работает, пока её оставлю...

Ладно, не загружайтесь, нужно что бы ещё кто нибудь сюда подошёл и сказал работает ли у него, а по одному мне судить я думаю не имеет смысла.

Еще раз спасибо за отклик

**Comment by Ved-un** [comment]
Для инфы, забыл я вам сказать что я сюда пришёл к вам с Реддита - у того человека тоже не работает 
https://www.reddit.com/r/archlinux/comments/xgh8b6/notification_on_usb_plugging_unplugging/

**Comment by Ved-un** [comment]
Как сейчас я понял - проблема скорее всего в этом :
_"...Заставить правильно работать из правила udev сценарий, содержащий команду notify-send, может оказаться непростой задачей, потому что уведомления не будут выводиться на рабочий стол..."_

из Arch Wiki (udev) [https://wiki.archlinux.org/title/udev_(Русский)#Уведомления_на_рабочем_столе](https://wiki.archlinux.org/title/udev_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)#%D0%A3%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BD%D0%B0_%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%BC_%D1%81%D1%82%D0%BE%D0%BB%D0%B5)

**Comment by VHSgunzo** [comment]
Нет, проблема в тайловых оконных менеджерах, все эти переменные экспортируются из скрипта udev-notify, к которому обращается udev, при обработке правила и на нормальных DE уведомления появляются.
Что не так с BSPWM и ему подобными, я пока не знаю...

**Comment by VHSgunzo** [comment]
Мне нужно устанавливать Арч+BSPWM на виртуалку и проводить тесты, но пока нет на это времени.
